import sys
from pathlib import Path

import pandas as pd
import streamlit as st


PROJECT_ROOT = Path(
    __file__
).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(
        0,
        str(PROJECT_ROOT),
    )


from src.services.ml_prediction_service import (
    MLPredictionService,
)


DATA_PATH = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "all_matches.csv"
)

MODEL_PATH = (
    PROJECT_ROOT
    / "saved_models"
    / "match_model.joblib"
)


@st.cache_resource
def load_prediction_service(
) -> MLPredictionService:
    service = MLPredictionService(
        data_path=str(DATA_PATH),
        model_path=str(MODEL_PATH),
    )

    service.load()

    return service


def create_probability_table(
    prediction,
) -> pd.DataFrame:
    return pd.DataFrame(
        {
            "Result": [
                (
                    f"{prediction.home_team} "
                    "win"
                ),
                "Draw",
                (
                    f"{prediction.away_team} "
                    "win"
                ),
            ],
            "Probability": [
                prediction
                .home_win_probability,

                prediction
                .draw_probability,

                prediction
                .away_win_probability,
            ],
        }
    )


def display_prediction_factors(
    prediction,
) -> None:
    st.subheader(
        "Why did the model choose "
        "this result?"
    )

    st.caption(
        "These explanations summarize "
        "important match features used by "
        "the prediction system. They are "
        "not guarantees or exact causal "
        "model explanations."
    )

    positive_column, negative_column = (
        st.columns(2)
    )

    with positive_column:
        st.markdown(
            "### Factors supporting "
            "the prediction"
        )

        if (
            prediction
            .positive_factors
        ):
            for factor in (
                prediction
                .positive_factors
            ):
                st.success(
                    f"**{factor.title}**\n\n"
                    f"{factor.explanation}"
                )

        else:
            st.info(
                "No strong supporting "
                "factor was identified."
            )

    with negative_column:
        st.markdown(
            "### Factors creating "
            "uncertainty"
        )

        if (
            prediction
            .negative_factors
        ):
            for factor in (
                prediction
                .negative_factors
            ):
                st.warning(
                    f"**{factor.title}**\n\n"
                    f"{factor.explanation}"
                )

        else:
            st.info(
                "No major opposing factor "
                "was identified."
            )


def main() -> None:
    st.set_page_config(
        page_title=(
            "Champions League "
            "ML Predictor"
        ),
        page_icon="🏆",
        layout="wide",
    )

    st.title(
        "🏆 Champions League "
        "ML Predictor"
    )

    st.write(
        "Predictions are generated by a "
        "machine-learning model trained on "
        "7,592 historical matches."
    )

    try:
        service = (
            load_prediction_service()
        )

    except Exception as error:
        st.error(
            "The ML prediction system "
            f"could not start: {error}"
        )

        st.stop()

    teams = service.get_teams()

    if len(teams) < 2:
        st.error(
            "At least two teams are "
            "required for prediction."
        )

        st.stop()

    home_column, away_column = (
        st.columns(2)
    )

    with home_column:
        default_home_index = 0

        if "FC Barcelona" in teams:
            default_home_index = (
                teams.index(
                    "FC Barcelona"
                )
            )

        home_team = st.selectbox(
            "Home team",
            options=teams,
            index=default_home_index,
        )

    with away_column:
        default_away_index = min(
            1,
            len(teams) - 1,
        )

        if "Celtic FC" in teams:
            default_away_index = (
                teams.index(
                    "Celtic FC"
                )
            )

        away_team = st.selectbox(
            "Away team",
            options=teams,
            index=default_away_index,
        )

    if home_team == away_team:
        st.warning(
            "Please select two "
            "different teams."
        )

        st.stop()

    predict_button = st.button(
        "Predict Match",
        type="primary",
        width="stretch",
    )

    if not predict_button:
        return

    try:
        prediction = service.predict(
            home_team=home_team,
            away_team=away_team,
        )

    except Exception as error:
        st.error(
            f"Prediction failed: {error}"
        )

        st.stop()

    st.subheader(
        f"{home_team} vs {away_team}"
    )

    first_metric, second_metric, third_metric = (
        st.columns(3)
    )

    with first_metric:
        st.metric(
            f"{home_team} win",
            (
                f"{prediction.home_win_probability:.1%}"
            ),
        )

    with second_metric:
        st.metric(
            "Draw",
            (
                f"{prediction.draw_probability:.1%}"
            ),
        )

    with third_metric:
        st.metric(
            f"{away_team} win",
            (
                f"{prediction.away_win_probability:.1%}"
            ),
        )

    result_column, confidence_column = (
        st.columns(2)
    )

    with result_column:
        st.metric(
            "Model prediction",
            prediction
            .predicted_result_text,
        )

    with confidence_column:
        st.metric(
            "Confidence",
            (
                f"{prediction.confidence_label} "
                f"({prediction.confidence:.1%})"
            ),
        )

    if (
        prediction.confidence_label
        == "LOW"
    ):
        st.warning(
            "The probabilities are close. "
            "This should be treated as a "
            "low-confidence prediction."
        )

    probability_table = (
        create_probability_table(
            prediction
        )
    )

    st.subheader(
        "ML result probabilities"
    )

    st.bar_chart(
        probability_table,
        x="Result",
        y="Probability",
    )

    st.divider()

    display_prediction_factors(
        prediction
    )

    st.divider()

    st.subheader(
        "Current team information"
    )

    home_summary = (
        service.get_team_summary(
            home_team
        )
    )

    away_summary = (
        service.get_team_summary(
            away_team
        )
    )

    summary_dataframe = pd.DataFrame(
        [
            {
                "Team": home_team,
                "Elo": (
                    home_summary[
                        "elo"
                    ]
                ),
                "Recent points per match": (
                    home_summary[
                        "form_points"
                    ]
                ),
                "Recent goals scored": (
                    home_summary[
                        "goals_scored"
                    ]
                ),
                "Recent goals conceded": (
                    home_summary[
                        "goals_conceded"
                    ]
                ),
                "Recent win rate": (
                    home_summary[
                        "win_rate"
                    ]
                ),
            },
            {
                "Team": away_team,
                "Elo": (
                    away_summary[
                        "elo"
                    ]
                ),
                "Recent points per match": (
                    away_summary[
                        "form_points"
                    ]
                ),
                "Recent goals scored": (
                    away_summary[
                        "goals_scored"
                    ]
                ),
                "Recent goals conceded": (
                    away_summary[
                        "goals_conceded"
                    ]
                ),
                "Recent win rate": (
                    away_summary[
                        "win_rate"
                    ]
                ),
            },
        ]
    )

    st.dataframe(
        summary_dataframe,
        width="stretch",
        hide_index=True,
    )

    st.caption(
        "Production model test accuracy: "
        "58.20% on 378 unseen Champions "
        "League matches. Individual "
        "predictions are probabilities, "
        "not guarantees."
    )


if __name__ == "__main__":
    main()